#act -l --container-architecture linux/amd64
# 푸시 이벤트 시작 (기본)
#  act
# 푸시 이벤트 시작 (기본), m1 mac일 경우
#  act --container-architecture linux/amd64
# 특정한 이벤트 시작
#  act pull_request
# 특정한 job만 실행하기
#  act -j job_name
# 특정한 workflow만 실행하기
#  act -j lint -W .github/workflows/checks.yml
name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build, unit tests and integration tests
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
